import mongoose from 'mongoose';

const ApplicationSchema = new mongoose.Schema({
  email: { type: String, required: true, unique: true, lowercase: true, trim: true },
  type: { type: String, required: true, enum: ['individual', 'company'] },
  country: { type: String, default: '' },
  individualName: { type: String, default: '' },
  nationalIdNumber: { type: String, default: '' },
  idProofName: { type: String, default: '' },
  idProofBase64: { type: String, default: '' },
  contactNumber: { type: String, default: '' },
  registeredAddress: { type: String, default: '' },
  pincode: { type: String, default: '' },
  mailingAddress: { type: String, default: '' },
  officialEmail: { type: String, default: '' },
  designation: { type: String, default: '' },
  workDescription: { type: String, default: '' },
  socialMediaHandles: { type: String, default: '' },
  companyName: { type: String, default: '' },
  companyRegNumber: { type: String, default: '' },
  regCertName: { type: String, default: '' },
  regCertBase64: { type: String, default: '' },
  gstin: { type: String, default: '' },
  companyContact: { type: String, default: '' },
  companyRegisteredAddress: { type: String, default: '' },
  companyPincode: { type: String, default: '' },
  companyMailingAddress: { type: String, default: '' },
  companyDescription: { type: String, default: '' },
  signatoryName: { type: String, default: '' },
  signatoryDesignation: { type: String, default: '' },
  signatoryEmail: { type: String, default: '' },
  companySocialMedia: { type: String, default: '' },
  copyrightCertName: { type: String, default: '' },
  copyrightCertBase64: { type: String, default: '' },
  services: { type: [String], required: true },
  pandadocDocumentId: { type: String, default: '' },
  pandadocStatus: { type: String, default: 'pending' },
  sessionId: { type: String, default: '' },
  createdAt: { type: Date, default: Date.now },
});

export default mongoose.models.Application || mongoose.model('Application', ApplicationSchema);
